
services:
  leginote-fe:
    image: node:20-alpine
    ports:
      - 3000:3000
    working_dir: /leginote-fe
    volumes:
      - /home/ubuntu/leginote-fe:/leginote-fe
    environment:
      - PORT=3000
    command: npm run start
    networks:
      - web
  traefik:
    image: traefik:v2.10
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.yml:/etc/traefik/traefik.yml
      - traefik_data:/data
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.leginote-fe.rule=Host(`localhost`)"
      - "traefik.http.routers.leginote-fe.entrypoints=web,websecure"
      - "traefik.http.routers.leginote-fe.tls.certresolver=myresolver"
      - "traefik.http.services.leginote-fe.loadbalancer.server.port=3000"

networks:
  web:
    driver: bridge

volumes:
  traefik_data:
