version: "3.8"
services:
  leginote-fe:
    image: node:20-alpine
    working_dir: /leginote-fe
    ports:
      - "3000:3000"
    volumes:
      - /home/ubuntu/leginote-fe:/leginote-fe
    environment:
      - PORT=3000
    command: npm run start

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /home/ubuntu/leginote-fe/.next:/leginote-fe/.next
    depends_on:
      - leginote-fe