server {
    listen 80;
    server_name leginote.statpan.com www.leginote.statpan.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name leginote.statpan.com www.leginote.statpan.com;

    ssl_certificate /etc/letsencrypt/live/leginote.statpan.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/leginote.statpan.com/privkey.pem;

    root /leginote-fe/public; # Serve static files from the public directory

    location /_next/static {
        alias /home/ubuntu/leginote-fe/.next/static;
        expires 365d;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}