name: Deploy to Oracle Cloud VM (on Pull Request)

on:
  workflow_dispatch:
  push:
    branches:
      - Statpan/issue6

env:
  PROJECT_DIR: /home/ubuntu/leginote-fe

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: leginote1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LEGINOTE1_SSH_KEY }}" > ~/.ssh/leginote1_ssh_key
          chmod 600 ~/.ssh/leginote1_ssh_key

      - name: Get Host Key and Add to known_hosts
        run: |
          ssh-keyscan -H -p ${{ secrets.LEGINOTE1_PORT }} ${{ secrets.LEGINOTE1_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy to Oracle Cloud VM
        run: |
          ssh -i ~/.ssh/leginote1_ssh_key -o UserKnownHostsFile=~/.ssh/known_hosts -p ${{ secrets.LEGINOTE1_PORT }} ${{ secrets.LEGINOTE1_USER }}@${{ secrets.LEGINOTE1_HOST }} \
            "bash -s" << EOF
              cd ${{ env.PROJECT_DIR }} || mkdir -p ${{ env.PROJECT_DIR }} && cd ${{ env.PROJECT_DIR }}
              rsync -avz --delete --exclude='node_modules' --exclude='.next' --exclude='public' . ${{ secrets.LEGINOTE1_USER }}@${{ secrets.LEGINOTE1_HOST }}:${{ env.PROJECT_DIR }}
              npm ci --legacy-peer-deps
              npm run build
              docker compose up -d --build
          EOF