name: Deploy to Oracle Cloud VM (on Pull Request)

on:
  workflow_dispatch:
  push:
    branches:
      - Statpan/issue6

env:
  PROJECT_DIR: /home/ubuntu/leginote-fe

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: leginote1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.LEGINOTE1_SSH_KEY }}" > ~/.ssh/leginote1_ssh_key
          chmod 600 ~/.ssh/leginote1_ssh_key

      - name: Get Host Key and Add to known_hosts
        run: |
          ssh-keyscan -H -p ${{ secrets.LEGINOTE1_PORT }} ${{ secrets.LEGINOTE1_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy to Oracle Cloud VM (Final Version)
        run: |
          # SSH 연결 및 명령어 실행 (개선 및 디버깅)
          ssh -i ~/.ssh/leginote1_ssh_key \
              -o UserKnownHostsFile=~/.ssh/known_hosts \
              -o StrictHostKeyChecking=no \
              -p ${{ secrets.LEGINOTE1_PORT }} \
              ${{ secrets.LEGINOTE1_USER }}@${{ secrets.LEGINOTE1_HOST }} \
              "bash -s" << 'EOF'  # 작은따옴표 사용

              set -e  # 오류 발생 시 즉시 중단
              set -x  # 실행되는 명령어 출력 (디버깅)

              # 작업 디렉토리 확인 및 생성
              cd "${PROJECT_DIR}" || { mkdir -p "${PROJECT_DIR}" && cd "${PROJECT_DIR}"; }
              pwd

              # rsync (개선)
              rsync -avz --delete \
                --exclude='node_modules' \
                --exclude='.next' \
                --exclude='public' \
                --progress \
                . ${{ secrets.LEGINOTE1_USER }}@${{ secrets.LEGINOTE1_HOST }}:"${PROJECT_DIR}"

              # npm 및 Docker Compose (오류 처리 개선)
              if ! npm ci --legacy-peer-deps; then
                echo "npm ci failed"
                exit 1
              fi

              if ! npm run build; then
                echo "npm run build failed"
                exit 1
              fi
              
              if [ ! -f docker-compose.yml ]; then
                echo "docker-compose.yml not found!"
                ls -la
                exit 1
              fi

              docker compose up -d --build
          EOF