name: Deploy to Oracle Cloud VM (on Pull Request)

on:
  workflow_dispatch:
  push:
    branches:
      - Statpan/issue6

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: leginote1

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Oracle Cloud VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LEGINOTE1_HOST }}
          port: ${{ secrets.LEGINOTE1_PORT }}
          username: ${{ secrets.LEGINOTE1_USER }}
          key: ${{ secrets.LEGINOTE1_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOST }} # 올바른 known_hosts 설정
          strict_host_key_checking: false

          script: |
            mkdir -p ${{ vars.PROJECT_DIR }}  # vars 컨텍스트 사용
            cd ${{ vars.PROJECT_DIR }}
            rsync -avz --delete --exclude 'node_modules' --exclude '.next' --exclude 'public' -e "ssh -p ${{ secrets.LEGINOTE1_PORT }}" . ${{ secrets.LEGINOTE1_USER }}@${{ secrets.LEGINOTE1_HOST }}:${{ vars.PROJECT_DIR }}
            npm ci
            npm run build
            docker compose up -d --build